filetype plugin on
filetype indent on

set number
syntax on

set path=$PWD/**
set linebreak

set expandtab shiftwidth=2 tabstop=2
set wildmode=longest,list,full

autocmd BufNewFile,BufRead *.slim setlocal filetype=slim
